# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "v1"
  name = "github.com/go-check/check"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/kata-containers/agent"
  revision = "827351a55b2886aa4ca4e663fab8e27a3bbb3a0b"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  version = "1.0.0-rc2"

[[constraint]]
  branch = "master"
  name = "github.com/rgbkrk/libvirt-go"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
